x-base-config: &base-config
  ports:
    - "11235:11235"  # Gunicorn port
  volumes:
    - /dev/shm:/dev/shm  # Chromium performance
  deploy:
    resources:
      limits:
        memory: 4G
      reservations:
        memory: 1G
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s

services:
  crawl4ai:
    # 1. Default: Pull multi-platform test image from Docker Hub
    # 2. Override with local image via: IMAGE=local-test docker compose up
    image: ${IMAGE:-unclecode/crawl4ai:${TAG:-latest}}
    container_name: crawl4ai-local
    privileged: true
    user: appuser
    hostname: crawl4ai
    networks: ["demo"]
    volumes:
      - ~/scripts:/app/scripts:rw
    # Local build config (used with --build)
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_TYPE: ${INSTALL_TYPE:-default}
        ENABLE_GPU: ${ENABLE_GPU:-false}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1G
    # Inherit shared config
    <<: *base-config

networks:
  demo:
    external: true